#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: ecb4219d7b7c0c3bfb358830bbe9301a68415471
    logging:
        logstash: # forward logs to ELK
            enabled: true
            host: docker.local
    metrics:
        logs: # report metrics in the logs
            enabled: true
            reportFrequency: 60 # in seconds

eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:admin@docker.local:8761/eureka/
