version: '2'
services:
    event-app:
        image: event
        external_links:
            - event-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/event?useUnicode=true&characterEncoding=utf8&useSSL=false
    event-mysql:
        extends:
            file: mysql.yml
            service: event-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
