version: '2'
services:
    app3-mysql:
        container_name: app3-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/app3/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=app3
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
