version: '2'
services:
    device-app:
        image: device
        external_links:
            - device-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/device?useUnicode=true&characterEncoding=utf8&useSSL=false
    device-mysql:
        extends:
            file: mysql.yml
            service: device-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
